import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SWRConfig } from "swr";
import "./globals.css";
import { ConfigProvider } from "@/context/ConfigContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SWRConfig
          value={{
            // Global SWR configuration to prevent API spamming
            revalidateOnFocus: false,      // Don't refetch when window regains focus
            revalidateOnReconnect: false,  // Don't refetch when reconnecting
            revalidateIfStale: false,      // Don't refetch stale data automatically
            dedupingInterval: 5000,        // Dedupe requests within 5 seconds
            shouldRetryOnError: true,      // Retry failed requests
            errorRetryCount: 3,            // Max 3 retries
            errorRetryInterval: 5000,      // Wait 5s between retries
            // Only revalidate based on refreshInterval (set per plugin)
          }}
        >
          <ConfigProvider>
            {children}
          </ConfigProvider>
        </SWRConfig>
      </body>
    </html>
  );
}
